
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST =
    "GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS =
    "GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE =
    "GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";



export const UPDATE_MENU_ITEMS_AVAILABILITY_REQUEST =
    "UPDATE_MENU_ITEMS_AVAILABILITY_REQUEST";
export const UPDATE_MENU_ITEMS_AVAILABILITY_SUCCESS =
    "UPDATE_MENU_ITEMS_AVAILABILITY_SUCCESS";
export const UPDATE_MENU_ITEMS_AVAILABILITY_FAILURE =
    "UPDATE_MENU_ITEMS_AVAILABILITY_FAILURE";