export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const UPDATE_STOCK = "UPDATE_STOCK";



export const GET_INGREDIENT_CATEGORY_REQUEST = "GET_INGREDIENT_CATEGORY_REQUEST";
export const GET_INGREDIENT_CATEGORY_SUCCESS = "GET_INGREDIENT_CATEGORY_SUCCESS";
export const GET_INGREDIENT_CATEGORY_FAILURE = "GET_INGREDIENT_CATEGORY_FAILURE";